# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/libris-maleficarum-service/src"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "nuget"
      - ".net"
    reviewers:
      - "PlagueHO"
    rebase-strategy: "auto"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "PlagueHO"
    rebase-strategy: "auto"
    groups:
      gh-actions:
        patterns:
          - "*"

  # NPM dependencies for React app
  - package-ecosystem: "npm"
    directory: "/libris-maleficarum-app"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "npm"
      - "react"
    reviewers:
      - "PlagueHO"
    rebase-strategy: "auto"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "all"
