/**
 * RFC 7807 Problem Details Types
 *
 * TypeScript interfaces for RFC 7807 Problem Details error responses from the backend API.
 * ASP.NET Core 7+ uses this format by default for structured error responses.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 * @see https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails
 */

/**
 * Base Problem Details structure per RFC 7807
 *
 * Represents a machine-readable format for specifying errors in HTTP API responses.
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it should provide human-readable documentation.
   * Default: "about:blank"
   */
  type?: string;

  /**
   * A short, human-readable summary of the problem type.
   * Should not change from occurrence to occurrence except for localization.
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence.
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * May be used to reference the error in logs.
   */
  instance?: string;

  /**
   * Additional members for extensibility.
   * Allows APIs to include custom error properties.
   */
  [key: string]: unknown;
}

/**
 * Validation Problem Details (ASP.NET Core format)
 *
 * Extended Problem Details structure used for validation errors.
 * ASP.NET Core model validation automatically returns this format.
 */
export interface ValidationProblemDetails extends ProblemDetails {
  /**
   * Validation errors organized by field name.
   * Each field can have multiple error messages.
   *
   * Example:
   * {
   *   "Name": ["The Name field is required.", "The Name field must be between 1 and 100 characters."],
   *   "Description": ["The Description field is required."]
   * }
   */
  errors: Record<string, string[]>;
}

/**
 * Type guard to check if error response is ValidationProblemDetails
 */
export function isValidationProblemDetails(
  error: ProblemDetails
): error is ValidationProblemDetails {
  return 'errors' in error && typeof error.errors === 'object';
}

/**
 * Type guard to check if an unknown value is ProblemDetails
 */
export function isProblemDetails(value: unknown): value is ProblemDetails {
  return (
    typeof value === 'object' &&
    value !== null &&
    'title' in value &&
    typeof (value as ProblemDetails).title === 'string' &&
    'status' in value &&
    typeof (value as ProblemDetails).status === 'number'
  );
}
