name: Continuous Integration

on:
  push:
    paths:
      - infra/**
      - docs/**
      - .github/workflows/**
      - libris-maleficarum-app/**
      - libris-maleficarum-service/**
  pull_request:
    branches:
      - main
    paths:
      - infra/**
      - docs/**
      - .github/workflows/**
      - libris-maleficarum-app/**
      - libris-maleficarum-service/**
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-markdown:
    name: Lint Markdown
    uses: ./.github/workflows/lint-markdown.yml

  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    uses: ./.github/workflows/lint-and-publish-bicep.yml

  build-frontend-app:
    name: Build Frontend App
    uses: ./.github/workflows/build-frontend-app.yml

  build-backend-service:
    name: Build Backend Service
    uses: ./.github/workflows/build-backend-service.yml

  build-docs:
    name: Build Docs
    uses: ./.github/workflows/build-docs.yml
    permissions:
      contents: read
