name: Lint and Publish Bicep

on:
  workflow_call:

jobs:
  build-armtemplates:
    name: Lint and Publish Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bicep
        run: |
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help

      - name: Lint Bicep
        run: |
          bicep lint ./infra/main.bicep

      - name: Publish Bicep as Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure_bicep
          path: |
            ./infra/main.bicep
            ./infra/abbreviations.json
            ./infra/core/
